CONFORMER_DIM = 300
CONFORMER_DEPTH = 16
CONFORMER_HEADS = 4
CONFORMER_DIM_HEAD = 36
CONFORMER_FEED_FORWARD_EXPANSION_FACTOR = 4
CONFORMER_CONV_EXPANSION_FACTOR = 2
CONFORMER_CONV_KERNEL_SIZE = 32


CONFORMER_BLOCK_ATTN_DROPOUT = 0
CONFORMER_BLOCK_FF_DROPOUT = 0
CONFORMER_BLOCK_CONV_DROPOUT = 0

SPEC_MEL_CHANNELS = 128
SPEC_FREQ_MIN = 20
SPEC_FREQ_MAX = 8000
SPEC_SAMPLE_RATE = 16000
SPEC_FRAME_SIZE = int(0.050 * SPEC_SAMPLE_RATE)
SPEC_HOP_LENGTH = int(0.0125 * SPEC_SAMPLE_RATE)